### ISSUE TITLE
TODO : generate Sphinx website gallery with Notebook examples

### ISSUE THREAD

**Issue by erwanp** [radis/spectro101#4]
Idea : let's have a stand-alone website to add some Radis-based Tutorials & Fun-Facts on Spectroscopy 

- [ ] set-up basic website. For convenience we could start from the radis/Fitroom website (https://github.com/radis/fitroom/tree/main/docs) ; also based on Radis 

- [ ] Host it on the ReadTheDocs pages or Github pages?

- [ ] Use nbsphinx : https://nbsphinx.readthedocs.io/en/0.6.1/subdir/gallery.html
